### ISSUE TITLE
[TODO] TODO LIST

### ISSUE THREAD

**Issue by alejzeis** [BlockServerProject/blockserverproject.github.com#2]
- [ ] create developer.blockserver.org
  - [ ] create basic site pages
    - [ ] make homepage
    - [ ] make contact us
    - [ ] choose a theme
    - [ ] choose the color theme
  - [ ] make error pages
    - [ ] 400 (required)
    - [ ] 401 (required)
    - [ ] 402
    - [ ] 403 (required)
    - [ ] 404 (required)
    - [ ] 405
    - [ ] 406
    - [ ] 407
    - [ ] 408
    - [ ] 409
    - [ ] 410
    - [ ] 411
    - [ ] 412
    - [ ] 413
    - [ ] 414
    - [ ] 500 (required)
    - [ ] 501
    - [ ] 502
    - [ ] 503
    - [ ] 504
    - [ ] 505
  - [ ] get drupal
  - [ ] make .htaccess

**Comment by butcher211** [comment]
is this still relevant?

**Comment by RealIronDev** [comment]
@butcher211 Well not really

**Comment by RealIronDev** [comment]
@butcher211 What r u planning to do to this repo

**Comment by butcher211** [comment]
im still trying to figure out if it would be better to use only bootstrap or bootstrap on top of drupal. normally i am using drupal+omega framework with sass but because this is an open source project, i thought, that the bootstrap framework would be better because of its popularity and more people could contribute to this project then.

thats was only the technical view.
i was planning to make first design scetches today and then i wanted to decide which cms/no-cms, framework would be good for this project. i have these open questions because this is my first site for a software project (and additionally the first one which is open source). and there i need to figure it the criteria for the site first. its a completely new level for me :)

did you have any plans too? first i wanted to discover the web for some inspirations now. maybe you already have more precise ideas and would like to present them?

**Comment by RealIronDev** [comment]
Wow, I did not understand anything you just said

**Comment by RealIronDev** [comment]
@butcher211 I don't code that much I only use bootstrap, html, and a little php

**Comment by RealIronDev** [comment]
@butcher211 We have old files on PocketBukkit/BeaconPE-Site

**Comment by butcher211** [comment]
ok, than it was maybe the right idea to use bootstrap. and because i think that using things which is already there is better than creating stuff completely from zero im a huge fan of cms, specially of drupal.

have you experiences with less or are you using just css?

**Comment by jython234** [comment]
I would prefer only bootstrap.

**Comment by butcher211** [comment]
@jython234 i was philosophizing today in the morning about the pros and cons of both. my results were:

bootstrap only:
pros would be that it would just be easier to host on github but the cons would be that it would be very hard to make a multilingual site or that we have to create for every "dev's post" or whatever a new html file.

drupal + bootstrap:
drupal has its translation files which are maintained by the community and is very good extendable. plus its easier to create new lay out with views/panels without changing template files or whatever.

why bootstrap?
i would prefer zurb foundation framework but because of bootstraps popularity its easier to learn to handle it. even if i would drupal, i told myself that the omega framework which is so good on drupal wouldnt be a good decision --> bootstrap would be easier. only con at using bootstrap: LESS. but the new alpha version of bootstrap "fixed" that issue because it's using SASS as css preprocessor. :)
but even if there is an alpha version of bootstrap i would prefer to use LESS because i dont like to use unstable software. (bootstrap4 is still in development)

what do you both think about my thoughts?

**Comment by RealIronDev** [comment]
@butcher211 Drupal + Bootstrap sound good, because of Drupal's simplicity and the handling of bootstrap, btw @jython234 Can you add me back to the team so I can get access this repo?

**Comment by jython234** [comment]
@butcher211 For now i would like to stick with github hosting until the project picks up speed (then it will be ok spend money on a VPS). So for now, just bootstrap.

**Comment by RealIronDev** [comment]
@jython234 If I can I'll cover the vps for now, but its 512 Mb Ram so we can't run anything big
